chile_causes = {
    '1.1.1.': ('HUMAN', 'Legal burning of forest harvest wastes (burning for reforestation)'),
    '1.1.10.': ('HUMAN', 'Illegal burning for fuel reduction (preventive forestry)'),
    '1.1.11.': ('HUMAN', 'Legal burning rebound in fuel reduction (preventive forestry)'),
    '1.1.12.': ('HUMAN', 'Illegal burning rebound in fuel reduction (preventive forestry)'),
    '1.1.13.': ('HUMAN', 'Legal burning with other forestry purposes (sanitary burning, wildlife management, etc.)'),
    '1.1.14.': ('HUMAN', 'Illegal burning with other forestry purposes (sanitary burning wildlife management etc.)'),
    '1.1.15.': ('HUMAN', 'Reboot of legal burning for other forestry purposes'),
    '1.1.16.': ('HUMAN', 'Rebound of illegal burning for other forestry purposes'),
    '1.1.17.': ('HUMAN', 'Fire use in forest camp area'),
    '1.1.18.': ('HUMAN', 'Chainsaw spark in forestry work'),
    '1.1.19.': ('HUMAN', 'Spark machinery in forestry (skidder tractor light and heavy vehicle)'),
    '1.1.2.': ('HUMAN', 'Illegal burning of forest harvest wastes (burning for reforestation)'),
    '1.1.20.': ('HUMAN', 'Fire of forest site machinery (skidder chainsaw sawmill truck)'),
    '1.1.21.': ('HUMAN', 'Electric cable cutting forestry product'),
    '1.1.22.': ('HUMAN', 'Otros incendios por faenas forestales no clasificadas'),
    '1.1.23.': ('HUMAN', 'Use of fire in forestry areas (food heating other)'),
    '1.1.3.':  ('HUMAN', 'Reboot of legal burning of forest harvest'),
    '1.1.4.': ('HUMAN', 'Rebound of illegal burning of forest harvest'),
    '1.1.5.': ('HUMAN', 'Legal burning of forest land clearance (burning for afforestation)'),
    '1.1.6.': ('HUMAN', 'Illegal burning of forest land clearance (burning for afforestation)'),
    '1.1.7.': ('HUMAN', 'Reboot of legal burning in forest land clearance'),
    '1.1.8.': ('HUMAN', 'Rebound of illegal burning in forest land clearance'),
    '1.1.9.': ('HUMAN',  'Legal burning for fuel reduction (preventive forestry)'),
    '1.10.1.': ('HUMAN', 'Military maneuvers'),
    '1.10.2.': ('HUMAN', 'Mining tasks'),
    '1.10.3.': ('HUMAN', 'Explosions (oil pipelines fuel tanks)'),
    '1.10.4.': ('HUMAN', 'Smoking habit'),
    # This is the worlds most thorough cause information i guarantee pls kill meeeeee
    '1.10.5.': ('HUMAN', 'Welding and assembly of various structures (high voltage towers, pipelines, etc.)'),
    '1.10.6.': ('HUMAN', 'Other activities not classified (brick cooking)'),
    '1.2.1.': ('HUMAN', 'Legal burning of agricultural waste'),
    '1.2.10.': ('HUMAN', 'Other fires due to unclassified agricultural work'),
    '1.2.2.': ('HUMAN', 'Illegal burning of agricultural waste'),
    '1.2.3.': ('HUMAN', 'Legal burning with other agricultural purposes (other sanitary burning)'),
    '1.2.4.': ('HUMAN', 'Illegal burning with other agricultural purposes (other sanitary burning)'),
    '1.2.5.': ('HUMAN', 'Agricultural machinery machinery spark'),
    '1.2.6.': ('HUMAN', 'Electrical cable cutting agricultural slaughter product'),
    '1.2.7.': ('HUMAN', 'Use of fire in livestock activities (other grassland management)'),
    '1.2.8.': ('HUMAN', 'Fire of agricultural machinery'),
    '1.2.9.': ('HUMAN',  'Use of fire in agricultural work areas (food and heating)'),
    '1.3.1.': ('HUMAN', 'Coal processing'),
    '1.3.2.': ('HUMAN', 'Use of fire at the site of extraction of fungi and fruits (rose hip strawberry pine nuts coconuts palm honey honey fungi others)'),
    '1.3.3.': ('HUMAN', 'Use of fire in the extraction and / or production of non-industrial firewood'),
    '1.3.4.': ('HUMAN', 'Use of fire in the extraction of other secondary forest products (quillay bark boldo palm honey)'),
    '1.4.1.': ('HUMAN', 'Use of fire for recreational activities in non-enabled areas (roaming hikers)'),
    '1.4.2.': ('HUMAN', 'Use of fire in hunting activities'),
    '1.4.3.': ('HUMAN', 'Use of fire in camping areas'),
    '1.4.4.': ('HUMAN', 'Use of fire in fishing activities'),
    '1.4.5.': ('HUMAN', 'Children playing with fire'),
    '1.4.6.': ('HUMAN', 'Fireworks'),
    '1.5.1.': ('HUMAN', 'Friction by friction in railway line by train or motorway passage'),
    '1.5.2.': ('HUMAN', 'Use of fire in maintenance of railway lines'),
    '1.5.3.': ('HUMAN', 'Railway accident'),
    '1.5.4.': ('HUMAN', 'Spark or cut of power lines of railway line'),
    '1.6.1.': ('HUMAN', 'Previous fire rebound declared controlled'),
    '1.6.2.': ('HUMAN', 'Fall of helicopter aircraft or other aircraft in forest firefighting operations or zone surveys'),
    '1.6.3.': ('HUMAN', 'Structural fire (house room forest camp or other buildings)'),
    '1.7.1.': ('HUMAN', 'Use of fire by passersby'),
    '1.7.2.': ('HUMAN', 'Use of fire in religious activities of pilgrimage and veneration (animitas)'),
    '1.7.3.': ('HUMAN', 'Car accident or fire in transit'),
    '1.7.4.': ('HUMAN', 'Use of fire for road signs'),
    '1.7.5.': ('HUMAN', 'Fall of helicopter or other aircraft in activities or operations other than forest fires'),
    '1.8.1.': ('HUMAN', 'Burning of garbage or other unclassified waste (other than authorized landfills or landfills)'),
    '1.8.10.': ('HUMAN', 'Reboot of legal burning for road cleaning gutter channels on public roads'),
    '1.8.12.': ('HUMAN', 'Burning of industrial waste'),
    '1.8.13.': ('HUMAN', 'Use of fire to eliminate unwanted fauna (reptile rodents, other wasps)'),
    '1.8.14.': ('HUMAN', 'Ignition of landfills or authorized landfills'),
    '1.8.2.': ('HUMAN', 'Legal burning of sawdust or sawdust on'),
    '1.8.3.': ('HUMAN', 'Illegal burning of sawdust or sawdust on'),
    '1.8.4.': ('HUMAN', 'Legal burning for road cleaning gutter channels in rustic properties'),
    # why did i choose this life
    '1.8.5.': ('HUMAN', 'Illegal burning for road cleaning gutter channels in rustic properties'),
    '1.8.6.': ('HUMAN', 'Rebrote of legal burning for road cleaning gutter channels in rustic properties'),
    '1.8.7.': ('HUMAN', 'Rebrote of illegal burning for road cleaning gutter channels in rustic properties'),
    '1.8.8.': ('HUMAN', 'Legal burning for road cleaning gutter channels on public roads'),
    '1.8.9.': ('HUMAN', 'Illegal burning for road cleaning gutter channels on public roads'),
    '1.8.11.': ('HUMAN', 'Illegal burning rebound for road cleaning gutter channels on public roads'),
    '1.9.1.': ('HUMAN', 'Electrical cable cut due to branch drop (except forestry work)'),
    '1.9.2.': ('HUMAN', 'Cable cut due to growth of vegetation under power lines'),
    '1.9.3.': ('HUMAN', 'Cable cut due to power drop or posting'),
    '1.9.4.': ('HUMAN', 'Cable cut for another accident or unclassified action'),
    '2.1.1.': ('HUMAN', 'Pyromaniac'),
    '2.1.10.': ('HUMAN', 'Caused to observe forest fire fighting operations'),
    '2.1.11.': ('HUMAN', 'Other intentional causes'),
    '2.1.2.': ('HUMAN', 'Conflict between people (revenge family conflicts and other passionate)'),
    '2.1.3.': ('HUMAN', 'Attack arsonist by conflict'),
    '2.1.4.': ('HUMAN', 'Territorial or patrimonial conflict'),
    '2.1.5.': ('HUMAN', 'Caused by a sick person (crazy or insanely excluded the arsonist)'),
    '2.1.6.': ('HUMAN', 'Caused by person under the influence of alcohol and / or drugs'),
    '2.1.7.': ('HUMAN', 'Caused to obtain economic benefits (purchase of wood pressure for work etc.)'),
    '2.1.8.': ('HUMAN', 'Vandalism'),
    '2.1.9.': ('HUMAN', 'Terrorism or subversion (excluding incendiary attack)'),
    '3.1.1.': ('NATURAL-LIGHTNING', 'Lightning strike'),
    '3.1.2.': ('NATURAL-VOLCANO', 'Volcano'),
    '3.1.3.': ('NATURAL', 'Otras causas naturales no clasificadas'), # will change the schema later from lightning to natural to accommodate volcanoes, etc.
    '4.1.1.': ('UNKNOWN', 'Unknown (investigated but it is not possible to establish the root cause)'),
    '4.1.2.': ('UNKNOWN', 'No determinada (la causa no es investigada)')
}