# Generated by Django 2.2.5 on 2019-12-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fireapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fires',
            options={'managed': True},
        ),
    ]
