# Generated by Django 2.2.5 on 2019-12-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fireapi', '0002_auto_20191221_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fires',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fires',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fires',
            name='start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='fires',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
