# Generated by Django 2.2.5 on 2019-12-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fireapi', '0004_auto_20191221_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fires',
            options={'managed': False},
        ),
    ]
